---

# A sample PHP playbook

  - hosts: php

    become: yes
    become_user: "root"
    become_method: "sudo"

    # Customize vars for Apache, PHP or MySQL (see mysql playbook)
    # vars:

    roles:
      - { role: php-apache2, tags: ['php','apache2'] }

      # Alternative role
      # - { role: php-nginx, tags: ['php','nginx'] }

      # You can add MySQL and MongoDB roles here...
      # - { role: mysql, tags: ['mysql'] }
      # - { role: mongodb, tags: ['mongodb'] }

    tasks:

      # Add MySQL tasks here (see mysql playbook)

      # Add Apache tasks here
      - name: copy app vhost file
        copy:
          src: etc/apache2/vhost.conf
          dest: /etc/apache2/sites-available/000-app.conf
          owner: root
          group: root
          mode: 0644

      - name: enable website
        command: "a2ensite 000-app"
        args:
          creates: "/etc/apache2/sites-enabled/000-app.conf"
        notify:
          - reload apache2

      # See https://docs.ansible.com/ansible/composer_module.html
      - name: run composer install
        composer:
          command: install
          working_dir: /app

      - name: Hello PHP
        action: shell echo "Hello PHP!"
        register: result
      - debug: var=result.stdout

    handlers:
      - name: restart apache2
        action: service name=apache2 state=restarted

      - name: reload apache2
        action: service name=apache2 state=reloaded
